### PR TITLE
netstandard support

### PR DESCRIPTION
**Pull request by tomcurran**
Build script had to be forced to pick up msbuild path. Not sure if cake need updating to support newer features like this? Not sure about the windows / unix stuff in the build script but tried to keep it supporting both without being able to test it on windows.

iOS project configuration has automatically changed slightly. @b099l3 can you review that?

Test & samples projects have not been tested with this yet.

### CODE REVIEW

**Comment by b099l3** [comment]
iOS config looks ok, it took out MtouchUseRefCounting but thats fine as its an old settings, the garabage collector will handle this

**Comment by b099l3** [comment]
Also should we not look into removing appveyor as a check on this, think it will always fail due to env vars

**Comment by b099l3** [comment]
Also I like the shared project approach, seems abit "cleaner" imo. :shipit:

**Comment by tomcurran** [comment]
I wasn't sure about anything related to appveyor as you set it up but if it isn't needed any more than yeah we should remove it. @b099l3 could you do that?

I tried to push CrossIceCreamMachine into the shared project but couldn't get it to work. Will have another go.

**Comment by b099l3** [comment]
Aye cool I'll remove the appveyor check

**Comment by b099l3** [comment]
Removed.

**Pull request merged**
